### ISSUE TITLE
Node install doesn't work

### ISSUE THREAD

**Issue by fzaninotto** [iros/underscore.nest#2]
Did as explained in the docs, but got a problem:

``` js
// in main.js
var u =  require('underscore');
u.nest = require('underscore.nest');
```

``` sh
> node main
in foo/node_modules/underscore.nest/underscore.nest.js:103
}(this, _));
        ^
ReferenceError: _ is not defined
    at Object.<anonymous (foo/node_modules/underscore.nest/underscore.nest.js:103:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (foo/main.js:2:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by vsviridov** [comment]
It works if you do

``` javascript
_ = require('underscore');
_.nest = require("underscore.nest");
```

Notice the lack of `var` before `_`.
It is quite dirty and needs fixing though.
